# syntax=docker/dockerfile:1

FROM koalaman/shellcheck-alpine:v0.7.1@sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252 AS shellcheck
WORKDIR /go/src/github.com/docker/cli
RUN --mount=type=bind,target=. \
  set -eo pipefail; \
  find scripts/ contrib/completion/bash -type f | grep -v scripts/winresources | grep -v '.*.ps1' | xargs shellcheck
